// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjHatOseNwSPU7AA6SHzlDtSB03HuXEI',
    appId: '1:445433521549:web:b4e8539becd46313ca49c4',
    messagingSenderId: '445433521549',
    projectId: 'cloudnotes-cf807',
    authDomain: 'cloudnotes-cf807.firebaseapp.com',
    storageBucket: 'cloudnotes-cf807.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTjYZ8LUpl-A5wp6TMHmRlyB_UztH12A',
    appId: '1:445433521549:android:cc0268a1d6aacc94ca49c4',
    messagingSenderId: '445433521549',
    projectId: 'cloudnotes-cf807',
    storageBucket: 'cloudnotes-cf807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrX5ISzLV4zmwBWyZnnqbxvLsY4kmCuM4',
    appId: '1:445433521549:ios:db8ef5f5b9c82369ca49c4',
    messagingSenderId: '445433521549',
    projectId: 'cloudnotes-cf807',
    storageBucket: 'cloudnotes-cf807.firebasestorage.app',
    iosBundleId: 'com.example.cloudNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrX5ISzLV4zmwBWyZnnqbxvLsY4kmCuM4',
    appId: '1:445433521549:ios:db8ef5f5b9c82369ca49c4',
    messagingSenderId: '445433521549',
    projectId: 'cloudnotes-cf807',
    storageBucket: 'cloudnotes-cf807.firebasestorage.app',
    iosBundleId: 'com.example.cloudNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhjHatOseNwSPU7AA6SHzlDtSB03HuXEI',
    appId: '1:445433521549:web:82ef18a0f1e9630cca49c4',
    messagingSenderId: '445433521549',
    projectId: 'cloudnotes-cf807',
    authDomain: 'cloudnotes-cf807.firebaseapp.com',
    storageBucket: 'cloudnotes-cf807.firebasestorage.app',
  );
}
